local Library = loadstring(game:HttpGet("https://raw.githubusercontent.com/xHeptc/Kavo-UI-Library/main/source.lua"))()
local Window = Library.CreateLib("Penguin", "Ocean")

local DoorsTab     = Window:NewTab("Doors guis & scripts")
local DoorsSection = DoorsTab:NewSection("balls")
DoorsSection:NewButton("vynixius", "Creddit to vynixuis, this is an all around great script ", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/RegularVynixu/Vynixius/main/Loader.lua"))()
end)
DoorsSection:NewButton("entity spawner", "credit to the name of the guy on the script cus idk ", function()
    loadstring(game:HttpGet('https://raw.githubusercontent.com/StupidProAArsenal/main/main/deer%20customs',true))()
end)
DoorsSection:NewButton("inf yeild", "no credit boxo ", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/EdgeIY/infiniteyield/master/source"))()
end)
DoorsSection:NewButton("plamens gui", "credit to plamen", function()
    loadstring(game:HttpGet('https://raw.githubusercontent.com/plamen6789/DoorsEntitySummonerGUI/main/EntityGUI'))()
end)

DoorsSection:NewButton("sernox", "only paid executors woek lmmao", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/SernoxSergal/Sernox-s-Door-Gui/main/Gui"))()-- function
end)
     -- dSection:NewButton("hardcore", "made by ping funni but ima make this section not work", function()
      --  loadstring(game:HttpGet("https://pastebin.com/raw/UkqP7g6x"))()
    -- end)
DoorsSection:NewButton("old plamens", "works better", function()
    loadstring(game:HttpGet('https://raw.githubusercontent.com/plamen6789/OldEntityGUI/main/OldEntityGUI'))()
end)
DoorsSection:NewButton("doors", "script", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/PenguinManiack/op-doors-script/main/doors"))() -- function
end) 

local GunTab     = Window:NewTab("Doors Guns")
local GunSection = GunTab:NewSection("Guns")
GunSection:NewButton("gun zeppsy", "gun", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/ZepsyyCodesLUA/Utilities/main/DOORSFpsGun.lua?token=GHSAT0AAAAAAB2POHILOXMAHBQ2GN2QD2MQY3SXTCQ"))()-- loadstring-- function
end) 
GunSection:NewButton("dorrito gun", "dorito shooter", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/PenguinManiack/every-gun/main/dorito"))() -- functio 
end)
GunSection:NewButton("christmas gun", "desc", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/PenguinManiack/every-gun/main/cristmas"))() -- function
end)
GunSection:NewButton("turkey leg gun", "shoots turkey legs", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/PenguinManiack/every-gun/main/turkey%20leg"))()
end)
GunSection:NewButton("weiner", "weiners hehe", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/PenguinManiack/every-gun/main/screech%20gun"))()
end)
GunSection:NewButton("dorrito bag", "shoots doritos", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/PenguinManiack/every-gun/main/dorrito%20bag%20gun"))()
end)
GunSection:NewButton("regulair m429", "just a regulair gun", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/PenguinManiack/every-gun/main/regulair%20m429"))() -- function
end)
GunSection:NewButton("phys gun", "the guy who made it", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/SernoxSergal/Sernox-s-Door-Gui/main/PhysGun.lua"))()
end)
GunSection:NewButton("Christmass balls", "goes crazyyyyy", function()
    loadstring(game:HttpGet('https://raw.githubusercontent.com/PenguinManiack/every-gun/main/christmas%20balls'))()
end)

local Credits    = Window:NewTab("Credits")
local Credits = Credits:NewSection("crdit to PenguinManiack for helping with the guns and GUI cleanup")